### ISSUE TITLE
Problem on the ErrorController when BaseErrorController is not on App namespace.

### ISSUE THREAD

**Issue by alysson-azevedo** [ozee31/cakephp-cors#1]
Since I don't use App as my namespace, [this line](https://github.com/ozee31/cakephp-cors/blob/master/src/Controller/ErrorController.php#L4) raises an error.

**Comment by alysson-azevedo** [comment]
i'm not sure if it works, but how about using `Cake\Core\App::classname('Error', 'Controller', 'Controller')` to return the correct ErrorController classname?

**Comment by ozee31** [comment]
OK, I see the problem.
I will try to do differently to get around the problem.

**Comment by AlanCrevon** [comment]
Same problem here :)

**Comment by AlanCrevon** [comment]
Looks like using 

`use Cake\Controller\ErrorController as BaseErrorController;` 

solves the problem here. @alysson-azevedo : you might want to test.

Edit : naaaa... This is not a universal solution. Forget about it. Sorry.

**Comment by ozee31** [comment]
Ok, with the new release you can change the ErrorController class.

In app.php you can write
```php
'Cors' => [
    'ErrorController' => 'Other\Namespace\ErrorController',
]
```

but in this controller you must add

```php
public function beforeRender(Event $event) {
    // ...
    $this->response->header(['Access-Control-Allow-Origin' => '*']);
}
```

It's OK for you ?

**Comment by alysson-azevedo** [comment]
seems good for me.
