### ISSUE TITLE
options 404

### ISSUE THREAD

**Issue by nomanbiniqbal** [ozee31/cakephp-cors#10]
After i implement this plugin and send options call it modified the response header but returning 404 not found error . 
please help.

**Comment by nomanbiniqbal** [comment]
i m using this to genrate resource
https://book.cakephp.org/3.0/en/development/routing.html#mapping-additional-resource-routes

**Comment by ozee31** [comment]
i look at that ASAP

**Comment by frankvanhest** [comment]
Sorry to say that this fix will now break applications which do not use the RoutingMiddleware. The following exception is thrown.
`[LogicException] No middleware matching 'Cake\Routing\Middleware\RoutingMiddleware' could be found.`
I've added a PR with a possible solution for this. Unfortunately there is no method available in the CakePHP MiddlewareQueue to check if a middleware is used, so my given solution smells a bit hacky.
See PR https://github.com/ozee31/cakephp-cors/pull/17

**Comment by ozee31** [comment]
Good job, it's merged, i create new release
