### ISSUE TITLE
Headers not present at `POST`

### ISSUE THREAD

**Issue by bobmulder** [ozee31/cakephp-cors#15]
I've added your plugin as documented. The `OPTIONS` call goes well, however the `POST` call doesn't work. It will return a `200` but I get the message: `Failed to load {myapiurl}: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access.`. It seems the CORS hearders are missing in my `POST` call:

`OPTIONS` call:
![schermafbeelding 2018-06-14 om 13 35 25](https://user-images.githubusercontent.com/5465074/41409898-148da234-6fd8-11e8-9d7d-7bc871a5c074.png)

`POST` call:
![schermafbeelding 2018-06-14 om 13 35 42](https://user-images.githubusercontent.com/5465074/41409900-14a71192-6fd8-11e8-89f0-677910883da4.png)

I can't find any issues in your code. Any hints?

Kind regards,

Bob

**Comment by bobmulder** [comment]
It seems #7 has something to do with it...

**Comment by ozee31** [comment]
I don't have that problem.

When I send a post request on a valid route : 

![success](https://user-images.githubusercontent.com/5025797/41466363-3e3be8d2-70a2-11e8-939e-60b4b047ae64.png)

When I send a post request on a route where I throw an exception :

![error](https://user-images.githubusercontent.com/5025797/41466362-3e23d80a-70a2-11e8-8e87-967fae52cf07.png)

And When I send a post request on a route that doesn't exist :

![notexist](https://user-images.githubusercontent.com/5025797/41466361-3e054d54-70a2-11e8-8d6f-f88ac41e2c12.png)

**Comment by bobmulder** [comment]
I figured out that the cors-related headers won't be added when an exception is thrown. I guess #7 is related to my issue

**Comment by ozee31** [comment]
Yes i look this Pull Request ASAP

**Comment by ozee31** [comment]
PR merged, it's ok for you?

**Comment by leonardomrl** [comment]
I have the same problem :(

**Comment by ozee31** [comment]
Do you use special plugins or components?

**Comment by leonardomrl** [comment]
It worked out my problem, the error was not in CORS, it's working perfectly for me
