### ISSUE TITLE
Problem when running IntegrationTestCases

### ISSUE THREAD

**Issue by Zuluru** [ozee31/cakephp-cors#18]
I am loading the plugin as normal in my Application's bootstrap function:

    $this->addPlugin('Cors', ['bootstrap' => true, 'routes' => false]);

Regular page loads work just fine. But when I'm running unit tests, IntegrationTestCase::_sendRequest calls

    $url = $dispatcher->resolveUrl($url);

and then

    $response = $dispatcher->execute($request);

Both of these calls apparently result in BasePlugin::bootstrap being called. So the CORS plugin's bootstrap.php is called twice. And the second time through, it overwrites the `baseExceptionRenderer` in the config with the value it put into exceptionRenderer the first time through. Which means that the AppExceptionRenderer class tries to extend itself, with predictable failure.

Is this some problem exclusive to my setup? Or have others simply not experienced unhandled errors during unit testing with this plugin in place?

Wonder if the bootstrap.php being called twice will also mean the middleware is registered in the queue twice, which might cause other problems?

**Comment by Zuluru** [comment]
Anyone have any thoughts on this?

**Comment by Zuluru** [comment]
Looks like #20 is a different symptom of the same problem.

**Comment by ozee31** [comment]
Pull request merged, thank you @Zuluru
