### ISSUE TITLE
'Access-Control-Expose-Headers' should be after the OPTIONS request

### ISSUE THREAD

**Issue by wschwarte** [ozee31/cakephp-cors#19]
So my custom headers were not exposed correctly. Moving the expose headers to after the preflght options request seems to fix this. 

Your code should move this outside the 
` if (strtoupper($request->getMethod()) === 'OPTIONS') { } `

then it works correctly.

**Comment by ozee31** [comment]
Fixed in https://github.com/ozee31/cakephp-cors/releases/tag/v.1.1.5
