### ISSUE TITLE
Upgrade to cakephp 4.0

### ISSUE THREAD

**Issue by octisfall** [ozee31/cakephp-cors#23]
> ozee31/cakephp-cors v1.1.7 requires cakephp/cakephp >=3.3.2 <4.0.0

Do you plan to upgrade the plugin ?

**Comment by ozee31** [comment]
Yes, I plan to migrate when I have some time.

**Comment by OneHatRepo** [comment]
Please do this. It's needed for a project.
Thanks!

**Comment by chrisShick** [comment]
I didn't see any major changes to the middleware layer of Cake 4.x. Shouldn't this work without any changes considering the CakePHP 3.x style invokable double pass middlewares are still supported for backwards compatibility.

**Comment by chrisShick** [comment]
@ozee31 @octisfall @OneHatRepo I have created a pull request to update this plugin to Cake 4.x

https://github.com/ozee31/cakephp-cors/pull/24

**Comment by chrisShick** [comment]
@ozee31 any updates here?

**Comment by ozee31** [comment]
https://github.com/ozee31/cakephp-cors/pull/24

Thanks @chrisShick and @rchavik
