### ISSUE TITLE
Cors\Error\AppExceptionRenderer override crud's JSON API one

### ISSUE THREAD

**Issue by eymen-elkum** [ozee31/cakephp-cors#5]
In the case that crud' json api listener is using, the error cors Exception Rendered overrides Crud\Error\JsonApiExceptionRenderer

how can we fix this?

**Comment by ayman-alkom** [comment]
I wonder if we can make the renderer applied conditional

**Comment by ozee31** [comment]
I will add the possibility of not modifying exceptionRenderer.

But if you don't use exceptionRenderer see https://github.com/ozee31/cakephp-cors#errorcontroller to activate CORS if you have an exception

**Comment by eymen-elkum** [comment]
thanks @ozee31 i will follow that

**Comment by bravo-kernel** [comment]
Any chance we can get an example of how to disable the CORS exception renderer when using JsonApiListener (so I can update [the blog](http://www.bravo-kernel.com/2017/03/how-to-make-your-cakephp-3-api-produce-jsonapi/#5-Enabling-CORS-middleware) so people won't have broken validation when following the tutorial.

**Comment by ozee31** [comment]
It's released:

just change cors config in your `app.php` like

```
'Cors' => [
	'exceptionRenderer' => false
]
```

**Comment by bravo-kernel** [comment]
Thanks, didn't get that. I will update the blog accordingly. Good job 👍

**Comment by ayman-alkom** [comment]
I can confirm that it is working, good job

**Comment by bravo-kernel** [comment]
Not working for me, I am not getting no JSON API errors and no validation errors. Anything I could be missing here?

**Comment by bravo-kernel** [comment]
Seems `false` doesn't quite do it for Crud's `JsonApiListener`. This however, does work:

```php
    'Cors' => [
        'exceptionRenderer' => '\Crud\Error\JsonApiExceptionRenderer'
    ],
```

**Comment by ayman-alkom** [comment]
@bravo-kernel with Api it seems working, but I didn't tried it with JsonApi

**Comment by eymen-elkum** [comment]
Hi @bravo-kernel I fixed it by using the deprecated header function in the error controller
my PR for this may caused this problem

```
    public function beforeRender(Event $event)
    {
        parent::beforeRender($event);

        //$this->response->withHeader('Access-Control-Allow-Origin:', '*');
        $this->response->header(['Access-Control-Allow-Origin' => '*']);
        $this->viewBuilder()->setTemplatePath('Error');
    }
```

**Comment by lpj145** [comment]
hey guys, i have same error, how did you solved ?
