### ISSUE TITLE
Add CORS to exception

### ISSUE THREAD

**Issue by lpj145** [ozee31/cakephp-cors#7]
How add CORS on any exceptions ? when i have code 422 or 409 CORS not enabled.

**Comment by ozee31** [comment]
Thank you for your issue, I look at this ASAP

**Comment by ozee31** [comment]
If you use default config, exception work with CORS.

But if you use an other ErrorController you can add this in you ErrorController:

```PHP
public function beforeRender(Event $event) {
    // ...
    $this->response = $this->response->withHeader('Access-Control-Allow-Origin', '*');
}
```

**Comment by ozee31** [comment]
Can you test the new release?
https://github.com/ozee31/cakephp-cors/releases/tag/v1.1.0

**Comment by andreyg-moby** [comment]
FYI,

It led to a problem in withCredentials cases where wildcard is not valid. Please try to keep CorsMiddleware logic even in exceptions.

**Comment by ozee31** [comment]
ok @andreyg-moby I would update Exceptions in the next release

**Comment by andreyg-moby** [comment]
@ozee31 as it hangs here for a while, I've added PR for my workaround: https://github.com/ozee31/cakephp-cors/pull/14

Please review, merge & release.
